version: '3'
services:
  server:
    build: .
    ports:
        - "7777:3000"
    links:
        - postgres
    environment:
        - DB_HOST=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DISABLE_NEWRELIC=true
  postgres:
    image: library/postgres
    ports:
        - "7778:5432"
    environment: 
        - POSTGRES_DB=epubpress_development
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
    